config/routes.rb
Rails.application.routes.draw do

  root                                       'static_pages#home'
  get    'home'                           => 'static_pages#home'
  get    'contact'                        => 'messages#new'
  get    'locations'                      => 'static_pages#locations'
  get    'about'                          => 'static_pages#about'
  get    'faq'                            => 'static_pages#faq'
  get    'search'                         => 'static_pages#search'
  post   'search'                         => 'static_pages#search'
  get    'mtbachelor'                     => 'guides#mtbachelor'
  get    'mthood'                         => 'guides#mthood'
  get    'mtwhistler'                     => 'guides#mtwhistler'
  get    'guides/:id/new-reservation'     => 'guides#new_reservation', as: :new_reservation
  get    'guides/:id/payment'             => 'guides#payment', as: :payment
  post   'reservation/:id/create'         => 'reservations#create', as: :create_reservation
  get    'users/:id/change_password'      => 'users#change_password', as: 'change_password'
  get    'signup'                         => 'users#new'
  get    'login'                          => 'sessions#new'
  get    'users/:id/transactions'         => 'users#transaction_history', as: 'transactions'
  get    'users/:id/review'               => 'users#review', as: 'review'
  post   'review'                         => 'reviews#new'
  post   'login'                          => 'sessions#create'
  delete 'logout'                         => 'sessions#destroy'
  get    'guides'                         => 'guides#index', as: 'index'

  resources :users
  resources :guides
  resources :messages
  resources :reviews

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include StaticPagesHelper
  def home
    #
  end

  def contact
    #
  end

  def about
    #
  end

  def faq
    #
  end
  def locations
    #
  end

  def search
    @search_string = params[:search]
    if !params[:search].blank?
      results = searchDB(@search_string)
      if !results.nil?
        if !results.empty?
          resultObj = results[0]

          # Detecting a String means a location was found
          if resultObj.instance_of? String
            @location = resultObj

          # Detecting an Array means only guides were found
          elsif resultObj.instance_of? Array
            @guide_list = resultObj

          # If this occurs, something broke in searchDB()
          else
            flash.now[:danger] = "Query resulted in error"
          end

          resultObj = results[1]
          if !resultObj.nil?
            @guide_list = resultObj
          end
        else
          flash.now[:danger] = "No results were found"
        end
      else
        # Should never reach this
        flash.now[:danger] = "No results returned"
      end
    end
    render 'search'
  end

  helper_method :first_method

  def first_method
    #your code
    alert "testing"
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def home_guides
    guides = Guide.limit(3)
  end

  def hood_guides
    guides = Guide.where(:hood => true)
  end

  def bachelor_guides
    guides = Guide.where(:bachelor => true)
  end

  def whistler_guides
    guides = Guide.where(:whistler => true)
  end

  def about_guides
    guides = Guide.limit(6)
  end

  def top_guides(guides)
    top_guides = []
    guides.each do |guide|
      if guide.reviews.count > 0
        average_rating = guide.reviews.average(:rating)
        if top_guides.empty? || top_guides[0].reviews.average(:rating) < average_rating
          if !top_guides[1].nil?
            top_guides[2] = top_guides[1]
          end
          top_guides[1] = top_guides[0]
          top_guides[0] = guide
        elsif top_guides[1].nil? || top_guides[1].reviews.average(:rating) < average_rating
          top_guides[2] = top_guides[1]
          top_guides[1] = guide
        elsif top_guides[2].nil? || top_guides[2].reviews.average(:rating) < average_rating
          top_guides[2] = guide
        end
      end
    end
    return top_guides
  end

  # Returns an array of up to two objects,where String is the
  # location, and Array is an array of guides.
  # There are four possible return values: results = [String]
  #                                        results = [Array]
  #                                        results = [String, Array]
  #                                        results = []
  def searchDB(string)
    results = []
    if !string.nil?
      string = string.downcase
      if string == "Mount Hood".downcase
        results.push "Mount Hood"
      elsif string == "Mount Bachelor".downcase
        results.push "Mount Bachelor"
      elsif string == "Whistler".downcase
        results.push "Whistler"
      end

      i = 0
      if !results[0].nil?
        i = 1
      end
      guides = []

      Guide.find_each do |guide|
        if guide.user.name.downcase == string
          guides.push(guide)
        end
      end
      results[i] =(guides)
    end
    results
  end

end

app/views/static_pages/about.html.erb
<!-- Page Content -->
<div class="container">

  <!-- Page Heading/Breadcrumbs -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header" style="text-align:center">About
      </h1>
    </div>
  </div>
  <!-- /.row -->

  <div class="row">
    <div class="col-md-12 col-sm-12 col-lg-12">
      <h2 style="text-align:center">Radventure Mission</h2>
      <p style="text-align:center">It is Radventure's mission to help travellers maximize their time, pocketbooks, and smiles while experiencing adventures in the great outdoors.</p>

    </div>
  </div>
  <!-- /.row -->

  <!-- Intro Content -->
  <div class="row">
    <h2 style="text-align:center">The Radventure Story</h2>
    <div class="col-md-6">
      <%= image_tag 'whistler.jpg', class: 'img_responsive', style: 'padding-top:5px; height:280px; width:540px' %>
    </div>
    <div class="col-md-6">

      <p>After parting ways with her “personal adventure guide” (aka break-up with boyfriend), Andrea felt a large void in her ability to really get out and about to experience the outdoors as she had before.  One day, as she was going for a run, she had an A-HA! moment that she was likely not alone in this feeling of frustration.  What if there were others out there with the desire to see, experience and conquer but they just need a local friend to help show them the way?  That was when Radventure was born.
      </p>
      <p>
        We’ve all been there. You’re in a rad new place, but aren’t quite sure where to start. You wish you had a local buddy to give you the inside scoop. You chat with ski techs, bike shop staff, and bartenders, but what you really want is local to show you the sick spots so you can make the most your time outside.
      </p>
    </div>
  </div>
  <!-- /.row -->

  <!-- Team Members -->
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header" style="text-align:center">Our Team</h2>
    </div>
    <div class="col-md-4 text-center">
      <div class="thumbnail">
        <%= image_tag 'courtney.png', class: 'img-responsive' %>
        <div class="caption">
          <h3>Courtney Gould<br>
            <small>Director of Product</small>
          </h3>
          <p>Courtney grew up in Colorado spending her free time exploring the mountains hiking and skiing. Her background working outdoor retail during college paved the way to a further employment and understanding of the outdoor industry and a deep love for the outdoors. Currently living in Portland, Courtney is a MBA student at Portland State, where Radventure was born. Courtney is handling product development with a focus on technical deployment. Outside of time spent on Radventure, Courtney spends the rest of her time racing bikes and cooking from scratch. </p>
        </div>
      </div>
    </div>
    <div class="col-md-4 text-center">
      <div class="thumbnail">
        <%= image_tag 'andrea.png', class: 'img-responsive' %>
        <div class="caption">
          <h3>Andrea Bouma<br>
            <small>Director of Supply Chain Management</small>
          </h3>
          <p>Andrea has always had a love for the outdoors which only grew after her move out west from Michigan 10 years ago.  Activities that she is passionate about include: snowsports, hiking, running, river adventuring, and generally having a good time out in the sun.   Andrea’s background is in systems development from her past life as a product development food scientist.  After completing a MBA in strategy and entrepreneurship from Portland State University, Andrea teamed up with Courtney and Robyn (two of the raddest members of her cohort) to create Radventure.  A nomad at heart, Andrea is stoked to hit the road and work 1:1 with future Radventure guides to create a robust network of people helping people maximize their time having fun in the great outdoors.</p>
        </div>
      </div>
    </div>
    <div class="col-md-4 text-center">
      <div class="thumbnail">
        <%= image_tag 'robyn.png', class: 'img-responsive' %>
        <div class="caption">
          <h3>Robyn Gelfand<br>
            <small>Director of Marketing</small>
          </h3>
          <p>Ski patroller, marketer, and ex-ski bum. Robyn’s love for the outdoors took off during a month-long Outward Bound course in the Elk Mountains of Colorado. It was there that she resolved to move to the mountains after college, and also to find a way to enable more people to enjoy the outdoors. After graduating from the University of Virginia, Robyn spent time teaching skiing in Steamboat Springs, CO before getting into marketing for brands including Coors Light, Miller Lite, and adidas. Robyn is currently a member of Mt. Hood Ski Patrol and a MBA student at Portland State University, and is managing marketing for Radventure.</p>
        </div>
      </div>
    </div>
  </div>


    <!-- Our Customers -->
    <div class="row">
      <div class="col-lg-12">
        <h2 class="page-header" style="text-align:center" >Our Top Guides</h2>
      </div>

      <% top_guides = top_guides(whistler_guides) %>
      <% two_guides = top_guides.take(2) %>

      <% two_guides.each do |guide| %>
        <% if !guide.nil? %>
          <div class="col-lg-2 col-md-3 col-sm-4">
            <div class="panel panel-default">
              <div class="panel-heading">
                <%= image_tag Gravatar.new(guide.user.email).image_url(:d => :mm, :s => 120), class: 'img img-responsive img-portfolio img-hover',
                            style: 'height:100px; width:200px; margin-bottom: 0px;' %>
                <h5><%= link_to guide.user.name, guide %></h5>
                <!-- <img class="img-responsive img-hover img-related" src="../img/guide-n-location/guide1.jpg" alt=""> -->
                <h5>Rating: <% stars = guide.reviews.average(:rating).round %>
                  <% stars.times do |i| %>
                    <span class="fa fa-star"></span>
                  <% end %>
                  <% (5 - stars).times do |i| %>
                      <span class="fa fa-star-o"></span>
                  <% end %>
                </h5>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>

      <% top_guides = top_guides(bachelor_guides) %>
      <% two_guides = top_guides.take(2) %>

      <% two_guides.each do |guide| %>
        <% if !guide.nil? %>
          <div class="col-lg-2 col-md-3 col-sm-4">
            <div class="panel panel-default">
              <div class="panel-heading">
                <%= image_tag Gravatar.new(guide.user.email).image_url(:d => :mm, :s => 120), class: 'img img-responsive img-portfolio img-hover',
                              style: 'height:100px; width:200px; margin-bottom: 0px;' %>
                <h5><%= link_to guide.user.name, guide %></h5>
                <!-- <img class="img-responsive img-hover img-related" src="../img/guide-n-location/guide1.jpg" alt=""> -->
                <h5>Rating: <% stars = guide.reviews.average(:rating).round %>
                  <% stars.times do |i| %>
                    <span class="fa fa-star"></span>
                  <% end %>
                  <% (5 - stars).times do |i| %>
                    <span class="fa fa-star-o"></span>
                  <% end %>
                </h5>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>

      <% top_guides = top_guides(hood_guides) %>
      <% two_guides = top_guides.take(2) %>

      <% two_guides.each do |guide| %>
        <% if !guide.nil? %>
          <div class="col-lg-2 col-md-3 col-sm-4">
            <div class="panel panel-default">
              <div class="panel-heading">
                <%= image_tag Gravatar.new(guide.user.email).image_url(:d => :mm, :s => 120), class: 'img img-responsive img-portfolio img-hover',
                              style: 'height:100px; width:200px; margin-bottom: 0px;' %>
                <h5><%= link_to guide.user.name, guide %></h5>
                <!-- <img class="img-responsive img-hover img-related" src="../img/guide-n-location/guide1.jpg" alt=""> -->
                <h5>Rating: <% stars = guide.reviews.average(:rating).round %>
                  <% stars.times do |i| %>
                    <span class="fa fa-star"></span>
                  <% end %>
                  <% (5 - stars).times do |i| %>
                    <span class="fa fa-star-o"></span>
                  <% end %>
                </h5>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>

    </div>
    <!-- /.row -->

    <hr>

  </div>
  <!-- /.container -->

  <!-- jQuery -->
  <script src="js/jquery.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="js/bootstrap.min.js"></script>

  <!-- Tracking -->
  <script src="//cdn.optimizely.com/js/2718120061.js"></script>
</div>

app/views/static_pages/contact.html.erb
<!-- Page Content -->
<div class="container">

  <!-- Page Heading/Breadcrumbs -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header" style="text-align:center">Contact Us
      </h1>
    </div>
  </div>
  <!-- /.row -->

  <!-- Content Row -->
  <div class="row">
    <!-- Map Column -->
    <div class="col-md-8">
      <!-- Embedded Google Map -->
      <iframe width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed"></iframe>
    </div>
    <!-- Contact Details Column -->
    <div class="col-md-4">
      <h3>Contact Details</h3>
      <p>
        Portland State University<br>Portland, OR 97201<br>
      </p>
      <p><i class="fa fa-phone"></i>
        <abbr title="Phone">P</abbr>: (503)-111-1121</p>
        <p><i class="fa fa-envelope-o"></i>
          <abbr title="Email">E</abbr>: <a href="mailto:name@example.com">radventureit@gmail.com</a>
        </p>
        <p><i class="fa fa-clock-o"></i>
          <abbr title="Hours">H</abbr>: Monday - Friday: 9:00 AM to 5:00 PM</p>
    </div>
  </div>
  <!-- /.row -->

  <br>
  <div id="contacts">
    <div class="row">
      <!-- Alignment -->
      <div class="col-sm-offset-3 col-sm-6">
        <!-- Form itself -->
        <form name="sentMessage" class="well" id="contactForm"  novalidate>
          <legend>Email Us</legend>
          <div class="control-group">
            <div class="controls">
              <input type="text" class="form-control"
              placeholder="Full Name" id="name" required
              data-validation-required-message="Please enter your name" />
              <p class="help-block"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="controls">
              <input type="email" class="form-control" placeholder="Email"
              id="email" required
              data-validation-required-message="Please enter your email" />
            </div>
          </div>

          <div class="control-group">
            <div class="controls">
              <textarea rows="10" cols="100" class="form-control"
              placeholder="Message" id="message" required
              data-validation-required-message="Please enter your message" minlength="5"
              data-validation-minlength-message="Min 5 characters"
              maxlength="999" style="resize:none"></textarea>
            </div>
          </div>
          <div id="success"> </div> <!-- For success/fail messages -->
          <button type="submit" class="btn btn-primary pull-right">Send</button><br />
        </form>
      </div>
    </div>
  </div>
</div>


<!-- JS FILES -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src="./js/bootstrap.min.js"></script>
<script src="./js/jqBootstrapValidation.js"></script>
<hr>

<!-- /.container -->

<!-- jQuery -->
<script src="js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

<!-- Tracking -->
<script src="//cdn.optimizely.com/js/2718120061.js"></script>

<!-- Contact Form JavaScript -->
<!-- Do not edit these files! In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
<script src="js/jqBootstrapValidation.js"></script>
<script src="js/contact_me.js"></script>

app/views/static_pages/home.html.erb
<!-- Header Carousel -->
<header id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <div class="fill" style="background-image:url('http://web.cecs.pdx.edu/~ankgupta/skiing.jpg'); opacity: 0.6;"></div>
      <div class="carousel-caption">
        <h1 style="color:#000000"><strong>Skiing</strong></h1>
      </div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url('http://web.cecs.pdx.edu/~ankgupta/snowboarding.jpg');  opacity: 0.6;"></div>
      <div class="carousel-caption">
        <h1 style="color:#000000"><strong>Snowboarding</strong></h1>
      </div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url('http://web.cecs.pdx.edu/~ankgupta/whistler.jpg');  opacity: 0.6;"></div>
      <div class="carousel-caption">
        <h1 style="color:#000000"><strong>Your Confusing Map</strong></h1>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>
</header>

<!-- Page Content -->
<div class="container">

  <!-- Marketing Icons Section -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">
        What is Radventure??
      </h1>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4><i class="fa fa-fw fa-check"></i>About Us</h4>
        </div>
        <div class="panel-body">
          <p>
            You’re in a rad new place, but aren’t quite sure where to start.
            You wish you had a local buddy to give you the inside scoop.
            You chat with ski techs, bike shop staff, and bartenders, but what
             you really want is a local that can show you around the sick spots
             so you can make the most your time outside.
          </p>
          <a href="about.html" class="btn btn-default">Learn More</a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4><i class="fa fa-fw fa-check"></i>Our Mission</h4>
          </div>
          <div class="panel-body">
            <p>
              It is Radventure's mission to help travellers maximize their time,
              pocketbooks, and smiles while experiencing adventures in the great
              outdoors.
              <br>
              We’ve all been there. You’re in a rad new place, but aren’t quite
              sure where to start. You wish you had a local buddy to give you the
              inside scoop. You chat with ski techs, bike shop staff, and bartenders,
              but what you really want is local to show you the sick spots so you
              can make the most your time outside.
            </p>
            <a href="about.html" class="btn btn-default">Learn More</a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4><i class="fa fa-fw fa-check"></i>Get Started</h4>
          </div>
          <div class="panel-body">
            <p style="margin-left:25px">
              <li>Create an account</li>
              <li>View a <%= link_to "Location", locations_path %></li>
              <li>Find a guide</li>
              <li>Book it!!</li>
              <li>Have a radventurous time!</li>
              <li>Write your review</li>
            </p>
            <a href="signup.html" class="btn btn-default">Sign Up</a>
            <a href="faq.html" class="btn btn-default">Questions?</a>
          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->

    <!-- Portfolio Section - Panels for Guide & Location-->
      <div class="row">
        <div class="col-lg-12">
           <h2 class="page-header">Guides & Locations</h2>
        </div>

        <div class="col-md-4 col-sm-6">
           <div class="panel panel-default">
             <div class="panel-heading">
                <%= image_tag 'mthood.jpg', class: 'img-responsive img-portfolio img-hover', style: 'height:200px; width:400px;
                   margin-bottom: 0px;' %>
                <h4><strong>Name: Mount Hood</strong></h4>
                <h4>Location: Portland, Oregon</h4>
                <a href="mthood.html" class="btn btn-primary">See More</a>
             </div>
           </div>
        </div>

        <div class="col-md-4 col-sm-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <%= image_tag 'mtbachelor.jpg', class: 'img-responsive img-portfolio img-hover', style: 'height:200px; width:400px;
                   margin-bottom: 0px;' %>
              <h4><strong>Name: Mount Bachelor</strong></h4>
              <h4>Location: Bend, Oregon</h4>
              <a href="mtbachelor.html" class="btn btn-primary">See More</a>
            </div>
          </div>
        </div>

        <div class="col-md-4 col-sm-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <%= image_tag 'mtwhistler.jpg', class: 'img-responsive img-portfolio img-hover', style: 'height:200px; width:400px;
                   margin-bottom: 0px;' %>
              <h4><strong>Name: Mount Whistler</strong></h4>
              <h4>Location: Vancouver, Canada</h4>
              <a href="mtwhistler.html" class="btn btn-primary">See More</a>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->

      <div class="row">

        <% home_guides.each do |guide| %>
          <div class="col-md-4 col-sm-6">
            <div class="panel panel-default">
            <!--  <a href="<%= guide_path(guide) %>"> -->
                <div class="panel-heading">
                  <%= image_tag Gravatar.new(guide.user.email).image_url(:d => :mm), class: 'img img-circle img-portfolio img-hover',
                    style: 'height:200px; width:325px; margin-bottom: 0px;' %>
                  <h4>Name:  <%= guide.user.name %> </h4>
                  <h4>Sports: <%= sports_string(guide.downhill, guide.crosscountry, guide.snowboard) %></h4>
                  <h4>Location: <%= location_string(guide.hood, guide.bachelor, guide.whistler) %></h4>

                  <h4>Rating:
                    <% stars = guide.reviews.average(:rating).round %>
                    <% stars.times do |i| %>
                        <span class="fa fa-star"></span>
                    <% end %>
                    <% (5 - stars).times do |i| %>
                        <span class="fa fa-star-o"></span>
                    <% end %>
                  </h4>

                  <a href="<%= guide_path(guide) %>" class="btn btn-primary">See More</a>
                </div>
            <!--  </a> -->
            </div>
          </div>
        <% end %>
      </div>
    <!-- /.row -->

    <hr>

<!--
<button type="button" onclick="alert 'testing'">Click Me!.....</button>
-->





  </div>
  <!-- /.container -->

  <!-- jQuery -->
  <script src="../javascripts/jquery.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="../javascripts/bootstrap.min.js"></script>
  <script src="../javascripts/bootstrap.js"></script>
  <!-- Tracking -->
  <script src="//cdn.optimizely.com/js/2718120061.js"></script>

  <!-- Script to Activate the Carousel -->
  <script>
  $('.carousel').carousel({
    interval: 5000 //changes the speed
  })
  </script>

app/views/static_pages/search.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header" style="text-align:center">Search
    </h1>
  </div>
</div>

<div class="row">
  <!-- Alignment -->
  <div class="col-sm-offset-2 col-sm-8 col-lg-8 well well-sm">
  <!-- Search bar -->
        <%= form_tag :controller => 'static_pages', :action => 'search', :method => 'get' do %>
            <%= text_field_tag :search, params[:search], :id => 'search_field', class: 'form-control' %>
            <br>
            <%= submit_tag "Search", :name => nil , class: 'btn-primary btn' %>
        <% end %>


          <!-- Check search string -->
        <% if !@search_string.nil? %>
          <% if @location.nil? and (@guide_list.nil? or @guide_list.empty?) %>
            The search for "<%= @search_string %>" yielded no results
          <% else %>
            Results for "<%= @search_string %>":
          <% end %>

          <!-- Location listing -->
          <% if !@location.nil? %>
              <h3>Locations</h3>
              <%= link_to @location, if    @location == "Mount Hood"     then mthood_url
                                     elsif @location == "Mount Bachelor" then mtbachelor_url
                                     elsif @location == "Whistler"       then mtwhistler_url
                                     end %>
          <% end %>

          <!-- Guide listings -->
          <style>
              table, th, td {
                  border: 2px solid black;
                  border-collapse: collapse;
              }
               th, td {
                  padding: 5px;
              }
          </style>

          <% if !@guide_list.nil? and !@guide_list.empty? %>
            <h3>Guides</h3>
            <table>
              <thead>
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Locations</th>
                <th>Sports</th>
                <th>Rating</th>
              </tr>
              </thead>
              <% @guide_list.each do |guide| %>
                <tr>
                  <td><%= link_to guide.user.name, guide %></td>
                  <td><%= guide.user.email %></td>
                  <td><%= location_string(guide.hood, guide.bachelor, guide.whistler) %></td>
                  <td><%= sports_string(guide.downhill, guide.crosscountry, guide.snowboard) %></td>
                  <td><%= if !guide.reviews.empty? then guide.reviews.average(:rating).to_s
                          else "N/A" end %></td>
                </tr>
              <% end %>
            </table>
          <% end %>
        <% end %>
      </div>
    </div>
<!-- Tracking -->
<script src="//cdn.optimizely.com/js/2718120061.js"></script>