config/routes.rb
Rails.application.routes.draw do

  root                                       'static_pages#home'
  get    'home'                           => 'static_pages#home'
  get    'contact'                        => 'messages#new'
  get    'locations'                      => 'static_pages#locations'
  get    'about'                          => 'static_pages#about'
  get    'faq'                            => 'static_pages#faq'
  get    'search'                         => 'static_pages#search'
  post   'search'                         => 'static_pages#search'
  get    'mtbachelor'                     => 'guides#mtbachelor'
  get    'mthood'                         => 'guides#mthood'
  get    'mtwhistler'                     => 'guides#mtwhistler'
  get    'guides/:id/new-reservation'     => 'guides#new_reservation', as: :new_reservation
  get    'guides/:id/payment'             => 'guides#payment', as: :payment
  post   'reservation/:id/create'         => 'reservations#create', as: :create_reservation
  get    'users/:id/change_password'      => 'users#change_password', as: 'change_password'
  get    'signup'                         => 'users#new'
  get    'login'                          => 'sessions#new'
  get    'users/:id/transactions'         => 'users#transaction_history', as: 'transactions'
  get    'users/:id/review'               => 'users#review', as: 'review'
  post   'review'                         => 'reviews#new'
  post   'login'                          => 'sessions#create'
  delete 'logout'                         => 'sessions#destroy'
  get    'guides'                         => 'guides#index', as: 'index'

  resources :users
  resources :guides
  resources :messages
  resources :reviews

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :guide
  has_many :reviews, dependent: :destroy
  has_many :reservations

  before_save { self.email = email.downcase }

  validates :name,
    presence: true,
    length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
    presence: true,
    length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }

   has_secure_password
  validates :password, length: { minimum: 6 }, on: :create
  validates :password, length: { minimum: 6 }, allow_blank: true, on: :update

  #VAILD_PHONE_REGEX = /(?:(?:\+?1\s*(?:[.-]\s*)?)?(?:(\s*([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]‌​)\s*)|([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]))\s*(?:[.-]\s*)?)([2-9]1[02-9]‌​|[2-9][02-9]1|[2-9][02-9]{2})\s*(?:[.-]\s*)?([0-9]{4})/
  validates :phone_number,
    presence: true,
    length: { minimum: 10 },
    :if => :phone_number
  # format: { with: VAILD_PHONE_REGEX }

  validates :age,
    presence: true,
    numericality: { only_integer: true, greater_than: 0, less_than: 130 }

  validates :address,
    presence: true,
    length: { maximum: 50 }

  validates :city,
    presence: true,
    length: { maximum: 30 }

  validates :state,
    presence: true,
    length: { maximum: 30 }

  validates :zipcode,
    presence: true,
    length: { minimum: 5, maximum: 10 }

  validates :country,
    presence: true,
    length: { maximum: 50 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost

    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  before_action :logged_in_user,    only: [:edit, :show, :update, :change_password, :transaction_history]
  before_action :correct_user,      only: [:edit, :show, :update, :change_password, :transaction_history]
  before_action :already_signed_up, only: [:new]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if not params[:user][:country] == 'United States of America'
      params[:user][:state] = "None"
    end
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Radventure"
      redirect_to home_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if params[:user][:password].nil?
      if not params[:user][:country] == 'United States of America'
        params[:user][:state] = "None"
      end
      if @user.update(user_params)
        flash[:success] = 'Profile has been updated'
        render 'edit'
      else
        render 'edit'
      end
    else
      if not @user.authenticate(params[:current_password])
        flash.now[:danger] = 'Your current password is not valid'
        render 'change_password'
      else
        if params[:user][:password].blank?
          flash.now[:danger] = 'No new password entered'
          render 'change_password'
        elsif params[:user][:password] != params[:user][:password_confirmation]
          flash.now[:danger] = 'New password does not match confirmation'
          render 'change_password'
        elsif @user.update(user_params)
          flash.now[:success] = 'Your password has been updated'
          render 'edit'
        else
          render 'change_password'
        end
      end
    end
  end

  def transaction_history
    @user_reservations = Reservation.where(user_id: current_user.id)
    if is_guide?
      @guide_reservations = Reservation.where(guide_id: current_guide.id)
    end
  end

  def review
    @user = User.find(params[:id])
    @guide = Guide.find_by(user_id: @user.id)
    @reservation = Reservation.find_by(user_id: current_user.id, guide_id: @guide.id)

    @review = Review.new
  end

  def change_password
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(
        :name,
        :email,
        :phone_number,
        :age,
        :password,
        :password_confirmation,
        :address,
        :city,
        :state,
        :zipcode,
        :country
      )
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def us_states
    [
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
    ]
  end

  def countries
    [
        ['Canada', 'Canada'],
        ['Mexico', 'Mexico'],
        ['United States of America', 'United States of America']
    ]
  end

end

app/views/users/change_password.html.erb
<% provide(:title, 'Change password') %>
<div class="row">
  <div class="col-lg-12">
     <h1 class="page-header" style="text-align:center">Password Update</h1>
  </div>
</div>


<div class="row">
    <div class="col-sm-offset-4 col-sm-4 col-lg-4 col-md-4 well">
        <%= form_for(@user) do |formElement| %>
            <form class='well'>

              <%= render 'shared/user_error_messages' %>

              <div class='control-group'>
                 <div class="controls text-center">
                    <%= formElement.label 'Current password' %>
                    <br>
                    <%= formElement.password_field 'current_password', class: 'form-control', id: 'current_password', name: 'current_password' %>
                 </div>
              </div>
              <br>

              <div class='control-group'>
                <div class="controls text-center">
                  <%= formElement.label 'New password' %>
                  <br>
                  <%= formElement.password_field :password, class: 'form-control' %>
                </div>
              </div>
              <br>

              <div class='control-group'>
                <div class="controls text-center">
                  <%= formElement.label 'New password confirmation'  %>
                  <br>
                  <%= formElement.password_field :password_confirmation, class: 'form-control' %>
                </div>
              </div>
              <br>

              <div class='control-group'>
                <div class="controls text-center">
                  <%= link_to "Cancel", edit_user_url(id: @user.id),  class: "btn btn-default"%>
                  <%= formElement.submit 'Confirm', class: 'btn btn-success'%>
                </div>
              </div>
              <br>
          </form>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Account Settings') %>
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header" style="text-align:center">Account Settings</h1>
  </div>
</div>

<div class="row">
  <!-- Alignment -->
  <div class="col-sm-offset-4 col-sm-6 col-lg-4 well well-sm">
    <legend>Settings</legend>
        <% if is_guide? %>
            <p>Already a guide?
            <%= link_to "Edit Guide Profile", edit_guide_url(id: current_guide.id),  class: "btn btn-primary btn-sm pull-right"%>
            </p>
            <br><br>
        <% else %>
            <p>Want to be a guide?
            <%= link_to "Become a guide", new_guide_url(id: current_user.id),  class: "btn btn-primary btn-sm pull-right"%>
            <br><br>
            </p>
        <% end %>

        <p>Want to change your password?
        <%= link_to "Change password", change_password_url(id: current_user.id),  class: "btn btn-primary btn-sm pull-right"%>
        </p>
        <br>
        <p>Want to view your transactions?
        <%= link_to "View Transactions", transactions_path , class: "btn btn-primary btn-sm pull-right"%>
        </p>
        <br><br>

        <legend>Account Information</legend>
        <%= form_for(@user) do |formElement| %>
            <form class='well well-sm'>
              <%= render 'shared/user_error_messages' %>

              <div class="control-group">
                <div class="controls text-center">
                    <%= formElement.label :name  %>
                    <%= formElement.text_field :name , class:'form-control text-center' %>
                </div>
              </div>
              <br>

              <div class="control-group">
                <div class="controls text-center">
                    <%= formElement.label :email %>
                    <%= formElement.email_field :email, class:'form-control text-center'  %>
                </div>
              </div>
              <br>

              <div class="control-group">
                <div class="controls text-center">
                    <%= formElement.label :phone_number, class: 'control-label' %>
                    <%= formElement.text_field :phone_number , class:'form-control text-center'  %>
                </div>
              </div>
              <br>

              <div class="control-group">
                <div class="controls text-center">
                   <%= formElement.label :age, class: 'control-label' %>
                   <%= formElement.text_field :age , class:'form-control text-center'  %>
                </div>
              </div>
              <br>

              <div class="control-group">
                <div class="controls text-center">
                   <%= formElement.label :address, class: 'control-label' %>
                   <%= formElement.text_field :address, class:'form-control text-center'  %>
                </div>
              </div>
              <br>

              <div class="control-group">
                <div class="controls text-center">
                  <%= formElement.label :city, class: 'control-label' %>
                  <%= formElement.text_field :city , class:'form-control text-center' %>
                </div>
              </div>
              <br>

              <div class="control-group">
                <div class="controls text-center">
                  <%= formElement.label :zipcode, 'ZIP code', class: 'control-label' %>
                  <%= formElement.text_field :zipcode , class:'form-control text-center' %>
                </div>
              </div>
              <br>

              <div class="control-group">
                <div class="controls text-center">
                  <%= formElement.label :country, class: 'control-label' %>
                  <br>
                  <%= formElement.select(:country, options_for_select(countries, current_user.country)) %>
                </div>
              </div>
              <br>

              <div class="control-group", id = 'state_control'>
                <div class="controls text-center">
                  <%= formElement.label :state, class: 'control-label' %>
                  <br>
                  <% if current_user.state == 'None' %>
                    <%= formElement.select(:state, options_for_select(us_states)) %>
                  <% else %>
                    <%= formElement.select(:state, options_for_select(us_states, current_user.state)) %>
                  <% end %>
                </div>
                <br>
              </div>


              <div class='form-group text-center'>
                <%= formElement.submit 'Save changes', class: 'btn btn-success'%>
              </div>

            </form>
        <% end %>
  </div>
</div>

<script>
    var country_start = $('#user_country :selected').val();
    if(country_start != 'United States of America') {
        $('#state_control').hide();
    } else {
        $('#state_control').show();
    }
    // when the country field changes
    $("#user_country").change(function() {
        var country = $('#user_country :selected').val();
        if(country != 'United States of America') {
            $('#state_control').hide();
        } else {
            $('#state_control').show();
        }
    });
</script>
<!-- Tracking -->
<script src="//cdn.optimizely.com/js/2718120061.js"></script>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header" style="text-align:center">Sign Up</h1>
  </div>
</div>

<div class="row">
   <div class="col-sm-6 col-sm-offset-3 well" style="text-align:center">
        <%= form_for(@user) do |formElement|%>
          <form class='well'>
            <%= render 'shared/user_error_messages' %>

            <legend>Account Information</legend>
            <div class="row">
              <div class="control-group col-sm-8 col-sm-offset-2">
                    <div class='form-group'>
                      <%= formElement.label :name, class: 'control-label' %>
                      <%= formElement.text_field :name , class: 'form-control' %>
                    </div>
              </div>
            </div>

            <div class="row">
              <div class="control-group col-sm-8 col-sm-offset-2">
                    <div class='form-group'>
                      <%= formElement.label :password, class: 'control-label' %>
                      <%= formElement.password_field :password , class: 'form-control' %>
                    </div>
              </div>
            </div>

            <div class="row">
              <div class="control-group col-sm-8 col-sm-offset-2">
                  <div class='form-group'>
                      <%= formElement.label :password_confirmation, 'Confirmation',
                                  class: 'control-label' %>
                      <%= formElement.password_field :password_confirmation , class: 'form-control'%>
                  </div>
              </div>
            </div>

            <div class="row">
              <div class="control-group col-sm-8 col-sm-offset-2">
                <div class='form-group'>
                  <%= formElement.label :email, class: 'control-label' %>
                  <%= formElement.email_field :email , class: 'form-control'%>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="control-group col-sm-8 col-sm-offset-2">
                  <div class='form-group'>
                      <%= formElement.label :phone_number, class: 'control-label' %>
                      <%= formElement.text_field :phone_number , class: 'form-control'%>
                  </div>
              </div>
            </div>

            <div class="row">
              <div class="control-group col-sm-8 col-sm-offset-2">
                  <div class='form-group'>
                      <%= formElement.label :age, class: 'control-label' %>
                      <%= formElement.text_field :age , class: 'form-control'%>
                  </div>
              </div>
            </div>

            <legend>Personal Information</legend>
            <p class="help-block control-group col-sm-8 col-sm-offset-2">Your personal information will not be shared with anyone. It will only be used for payment information and personal security</p>
            <br><br>
            <div class="row">
              <div class="control-group col-sm-8 col-sm-offset-2">
                 <div class='form-group'>
                  <%= formElement.label :address, class: 'control-label' %>
                  <%= formElement.text_field :address, 'size' => 103 , class: 'form-control'%>
                 </div>
              </div>
            </div>

            <div class="row">
              <div class="control-group col-sm-8 col-sm-offset-2">
                 <div class='form-group'>
                      <%= formElement.label :city, class: 'control-label' %>
                      <%= formElement.text_field :city, class: 'form-control' %>
                 </div>
              </div>
            </div>

            <div class="row">
              <div class="control-group col-sm-8 col-sm-offset-2">
                <div class='form-group'>
                  <%= formElement.label :zipcode, 'ZIP code', class: 'control-label' %>
                  <%= formElement.text_field :zipcode , class: 'form-control'%>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="control-group col-sm-8 col-sm-offset-2">
                <div class='form-group'>
                  <%= formElement.label :country, class: 'control-label' %>
                  <br>
                  <%= formElement.select(:country, options_for_select(countries)) %>
                  <br>
                </div>
              </div>
            </div>

            <div class="row", id = 'state_control'>
              <div class="control-group col-sm-8 col-sm-offset-2">
                <div class='form-group'>
                  <%= formElement.label :state, class: 'control-label' %>
                  <br>
                  <%= formElement.select(:state, options_for_select(us_states))  %>
                  <br>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="control-group col-sm-8 col-sm-offset-2">
                <div class="control">
                  By clicking <strong class="label label-primary">Create my account</strong>, you agree to the
                  <a href="" data-toggle="modal" data-target="#termsconditions">Terms and Conditions</a>
                  <p class="help-block"></p>
                </div>
              </div>
            </div>
            <div class="modal fade" id="termsconditions" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="z-index:99999999999">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="termsconditions">Terms & Conditions</h4>
                  </div>
                  <div class="modal-body">
                      <div>
                        <p>INSERT TERMS AND CONDITIONS HERE</p>
                      </div>
                      <button type="submit" class="btn btn-default">Okay</button>
                  </div>
                </div>
              </div>
            </div>

            <br>
            <div class="row">
              <div class="control-group col-sm-8 col-sm-offset-2">
              <div class='form-group'>
                <%= formElement.submit 'Create my account', class: "btn btn-success" %>
              </div>
              </div>
            </div>
          </form>
        <% end %>
   </div>
</div>

<script>
    var country_start = $('#user_country :selected').val();
    if(country_start != 'United States of America') {
        $('#state_control').hide();
    } else {
        $('#state_control').show();
    }
    // when the country field changes
    $("#user_country").change(function() {
        var country = $('#user_country :selected').val();
        if(country != 'United States of America') {
            $('#state_control').hide();
        } else {
            $('#state_control').show();
        }
    });
</script>
<!-- Tracking -->
<script src="//cdn.optimizely.com/js/2718120061.js"></script>

app/views/users/review.erb
<!-- Page Heading/Breadcrumbs -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header" style="text-align:center">Leave a Guide Review</h1>
  </div>
</div>
<!-- /.row -->

<!-- Registration Section -->
<div id="guide">
  <div class="row">
    <!-- Alignment -->
    <div class="col-sm-offset-3 col-sm-6">
      <!-- Form itself -->
      <%= form_for @review do |formElement| %>
          <%= render 'shared/review_error_messages' %>
          <legend>Radventure Review for</legend>
          <!--%= hidden_field_tag :user_id, current_user %-->
          <%= hidden_field_tag :guide_id, @guide.id %>
          <%= hidden_field_tag :reservation_id, @reservation.id %>
          <p><b>Guide: <%= @guide.user.name %>
            <br>Reservation Time: <%= @reservation.time %>
            <br>Location: <%= @reservation.location %>
          </b></p>
          <br>

          <legend>Title:
            <%= formElement.text_field :title , class:'form-control' %>
          </legend>
          <div class="row">
            <div class="control-group">
              <div class="controls">
                <p class="col-sm-1 help-block control-label">Rating:</p>
                <div class="col-xs-1">
                  <%= formElement.select(:rating, options_for_select(ratings)) %>
                  <!--/select-->
                </div>
                <p class="col-sm-3 help-block control-label">out of 5</p>
              </div>
            </div>
          </div>
          <div class="control-group">
            <p class="help-block"></p>
            <div class="controls">
              <%= formElement.text_area :content, 'rows' => 10, 'cols' => 100, class:'form-control',
                                        placeholder: "Write a Review",
                                        minlength: "5",
                                        maxlength: "999", style: "resize:none"%>
            </div>
            <p class="help-block"></p>
          </div>
          <% params[:res_id] = @reservation %>
          <%= formElement.submit 'Submit Review', class: "btn btn-primary btn-sm pull-right" %>
          <br>
      <% end %>
    </div>
  </div>
</div>
<!-- /.row -->

<hr>

<!-- /.container -->

<!-- JS FILES -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src="./js/bootstrap.min.js"></script>
<script src="./js/jqBootstrapValidation.js"></script>
<script src="./js/contact_me.js"></script>
<script src="./js/bootstrap-formhelpers-phone.js"></script>

<!-- jQuery -->
<script src="js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>
<!-- Tracking -->
<script src="//cdn.optimizely.com/js/2718120061.js"></script>
<!-- Contact Form JavaScript -->
<!-- Do not edit these files! In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
<script src="js/jqBootstrapValidation.js"></script>
<script src="js/contact_me.js"></script>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<script type="text/javascript">
  window.location="/guides/<%=@user.id%>"
</script>

app/views/users/transaction_history.html.erb
<!-- Page Heading/Breadcrumbs -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header" style="text-align:center">Transaction History</h1>
  </div>
</div>
<!-- /.row -->

<!-- Transaction Section -->
<div id="transactionHistory">
  <div class="row">
    <% if !@guide_reservations.nil? and !@guide_reservations.empty? %>
      <div class="control-group text-center">
        <h2>As a Guide</h2>
      </div>
      <table class="table table-responsive" style="table-layout: fixed">
      <!-- Transaction Heading-->
      <thread>
        <tr>
          <th>Date</th>
          <th>Location</th>
          <th>Price (per hour)</th>
          <th>User</th>
          <th>Payment Status</th>
          <th>Review</th>
        </tr>
      </thread>

      <% Array(@guide_reservations).each do |guide_reservation| %>
          <% user = guide_reservation.user %>
          <% review = Review.find_by(user_id: user.id,
                                     guide_id: current_guide.id) %>
          <!-- transaction -->
          <thread>
            <tr>
              <td><%=guide_reservation.time%></td>
              <td><%=guide_reservation.location%></td>
              <td><%=number_to_currency(guide_reservation.price)%></td>
              <td><%=guide_reservation.user.name %></td>
              <% if guide_reservation.payment_status == 'Paid' %>
                  <td class="text-success">
                    <i class="fa fa-check "></i> Paid
                  </td>
              <% elsif guide_reservation.payment_status == 'Denied' %>
                  <td class="text-danger">
                    <i class="fa fa-minus"></i> Declined
                  </td>
              <% else %>
                  <td class="text-warning">
                    <i class="fa fa-exclamation-circle"></i> Pending
                  </td>
              <% end %>
              <% if !review.nil?  %>
                  <td>Completed</td>
              <% else %>
                  <td>Not Submitted</td>
              <% end %>
            </tr>
          </thread>
      <% end %>
    </table>
    <% end %>

    <% if !@user_reservations.nil? and !@user_reservations.empty? %>
      <div class="control-group text-center">
        <h2>As a User</h2>
      </div>
      <table class="table table-responsive" style="table-layout: fixed">
          <!-- Transaction Heading-->
          <thread>
            <tr>
              <th>Date</th>
              <th>Location</th>
              <th>Price (per hour)</th>
              <th>Guide</th>
              <th>Payment Status</th>
              <th>Review</th>
            </tr>
          </thread>

          <% Array(@user_reservations).each do |user_reservation| %>
            <% review = Review.find_by(user_id: current_user.id,
                                       guide_id: user_reservation.guide.id) %>
            <% guide = user_reservation.guide %>
            <!-- transaction -->
            <thread>
              <tr>
                <td><%=user_reservation.time%></td>
                <td><%=user_reservation.location%></td>
                <td><%=number_to_currency(user_reservation.price)%></td>
                <td><%=link_to guide.user.name, guide %></td>
                <% if user_reservation.payment_status == 'Paid' %>
                  <td class="text-success">
                    <i class="fa fa-check "></i> Paid
                  </td>
                <% elsif user_reservation.payment_status == 'Denied' %>
                    <td class="text-danger">
                      <i class="fa fa-minus"></i> Declined
                    </td>
                <% else %>
                  <td class="text-warning">
                    <i class="fa fa-exclamation-circle"></i> Pending
                  </td>
                <% end %>
                <% if !review.nil?  %>
                  <td>Completed</td>
                <% else %>
                  <td><%= link_to "Not Submitted", review_url(guide.user.id) %></td>
              <% end %>
              </tr>
            </thread>
          <% end %>
        </table>
      <% end %>
  </div>
</div>
<!-- /.row -->
<!-- Tracking -->
<script src="//cdn.optimizely.com/js/2718120061.js"></script>