config/routes.rb
Rails.application.routes.draw do

  root                                       'static_pages#home'
  get    'home'                           => 'static_pages#home'
  get    'contact'                        => 'messages#new'
  get    'locations'                      => 'static_pages#locations'
  get    'about'                          => 'static_pages#about'
  get    'faq'                            => 'static_pages#faq'
  get    'search'                         => 'static_pages#search'
  post   'search'                         => 'static_pages#search'
  get    'mtbachelor'                     => 'guides#mtbachelor'
  get    'mthood'                         => 'guides#mthood'
  get    'mtwhistler'                     => 'guides#mtwhistler'
  get    'guides/:id/new-reservation'     => 'guides#new_reservation', as: :new_reservation
  get    'guides/:id/payment'             => 'guides#payment', as: :payment
  post   'reservation/:id/create'         => 'reservations#create', as: :create_reservation
  get    'users/:id/change_password'      => 'users#change_password', as: 'change_password'
  get    'signup'                         => 'users#new'
  get    'login'                          => 'sessions#new'
  get    'users/:id/transactions'         => 'users#transaction_history', as: 'transactions'
  get    'users/:id/review'               => 'users#review', as: 'review'
  post   'review'                         => 'reviews#new'
  post   'login'                          => 'sessions#create'
  delete 'logout'                         => 'sessions#destroy'
  get    'guides'                         => 'guides#index', as: 'index'

  resources :users
  resources :guides
  resources :messages
  resources :reviews

end

app/models/guide.rb
class Guide < ActiveRecord::Base
  belongs_to :user
  has_many :reviews
  has_many :reservations

  validates :user_id,
    presence: true,
    uniqueness: { case_sensitive: true }

  validates :hood,
    :inclusion => { :in => [true, false] }

  validates :bachelor,
    :inclusion => { :in => [true, false] }

  validates :whistler,
    :inclusion => { :in => [true, false] }

  validates :downhill,
    :inclusion => { :in => [true, false] }

  validates :crosscountry,
    :inclusion => { :in => [true, false] }

  validates :snowboard,
    :inclusion => { :in => [true, false] }

  validates :rate,
    presence: true,
    numericality: { greater_than_or_equal_to: 0, less_than: 1000 }

  validates :profile,
            presence: true,
            length: { maximum: 999 }

  validates :sun_avail,
    presence: true,
    length: { maximum: 40 }

  validates :mon_avail,
    presence: true,
    length: { maximum: 40 }

  validates :tues_avail,
      presence: true,
      length: { maximum: 40 }

  validates :wed_avail,
    presence: true,
    length: { maximum: 40 }

  validates :thurs_avail,
    presence: true,
    length: { maximum: 40 }

  validates :fri_avail,
    presence: true,
    length: { maximum: 40 }

  validates :sat_avail,
    presence: true,
    length: { maximum: 40 }
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  include SessionsHelper
  include GuidesHelper
  before_action :logged_in_user, only: [
    :new,
    :edit,
    :update,
    :new_reservation,
    :create_reservation
  ]
  before_action :correct_user,   only: [:new]
  before_action :correct_guide,  only: [:edit, :update]

  def index
    @guides = Guide.all
  end

  def show
    @guide = Guide.find(params[:id])
    @reviews = @guide.reviews.paginate(page: params[:page])
  end

  def new
    @guide = Guide.new
  end

  def create
    @guide = Guide.new(guide_params)

    @guide.user_id = current_user.id

    replace_null_avail(@guide.sun_avail)
    replace_null_avail(@guide.mon_avail)
    replace_null_avail(@guide.tues_avail)
    replace_null_avail(@guide.wed_avail)
    replace_null_avail(@guide.thurs_avail)
    replace_null_avail(@guide.fri_avail)
    replace_null_avail(@guide.sat_avail)

    if @guide.save
      user = current_user
      log_out
      log_in user
      flash[:success] = "Congratulations! You are now a guide"
      redirect_to @guide
    else
      render 'new'
    end
  end

  def edit
    @guide = Guide.find(params[:id])
  end

  def update
    @guide = Guide.find(params[:id])

    @guide.user_id = current_user.id

    replace_null_avail(@guide.sun_avail)
    replace_null_avail(@guide.mon_avail)
    replace_null_avail(@guide.tues_avail)
    replace_null_avail(@guide.wed_avail)
    replace_null_avail(@guide.thurs_avail)
    replace_null_avail(@guide.fri_avail)
    replace_null_avail(@guide.sat_avail)

    if @guide.update(guide_params)
      flash[:success] = 'Guide profile has been updated'
      redirect_to @guide
    else
      render 'edit'
    end
  end

  def mtbachelor
  end

  def mthood
  end

  def mtwhistler
  end

  def new_reservation
    @guide = Guide.find(params[:id])
    @reservation = Reservation.new
  end

  private
    def guide_params
      params.require(:guide).permit(
        :user_id,
        :hood,
        :bachelor,
        :whistler,
        :downhill,
        :crosscountry,
        :snowboard,
        :rate,
        :profile,
        :sun_avail,
        :mon_avail,
        :tues_avail,
        :wed_avail,
        :thurs_avail,
        :fri_avail,
        :sat_avail
      )
    end
end

app/helpers/guides_helper.rb
module GuidesHelper
  def hood_guides
    guides = Guide.where(:hood => true)
  end

  def bachelor_guides
    guides = Guide.where(:bachelor => true)
  end

  def whistler_guides
    guides = Guide.where(:whistler => true)
  end


  def location_string(hood, bachelor, whistler)
    comma = false
    str = ''
    if hood
      str << 'Mount Hood'
      comma = true
    end

    if bachelor
      if comma
        str << ', '
      end
      str << 'Mount Bachelor'
      comma = true
    end

    if whistler
      if comma
        str << ', '
      end
      str << 'Whistler'
    end

    return str
  end

  def sports_string(downhill, crosscountry, snowboard)
    comma = false
    str = ''
    if downhill
      str << 'Downhill Skiing'
      comma = true
    end

    if crosscountry
      if comma
        str << ', '
      end
      str << 'Crosscountry Skiing'
      comma = true
    end

    if snowboard
      if comma
        str << ', '
      end
      str << 'Snowboarding'
    end

    return str
  end

  def top_guides(guides)
    top_guides = []
    guides.each do |guide|
      if guide.reviews.count > 0
        average_rating = guide.reviews.average(:rating)
        if top_guides.empty? || top_guides[0].reviews.average(:rating) < average_rating
          if !top_guides[1].nil?
            top_guides[2] = top_guides[1]
          end
          top_guides[1] = top_guides[0]
          top_guides[0] = guide
        elsif top_guides[1].nil? || top_guides[1].reviews.average(:rating) < average_rating
          top_guides[2] = top_guides[1]
          top_guides[1] = guide
        elsif top_guides[2].nil? || top_guides[2].reviews.average(:rating) < average_rating
          top_guides[2] = guide
        end
      end
    end
    return top_guides
  end

  def replace_null_avail(avail)
    if avail.blank?
      avail.replace('Unavailable')
    end
  end
end

app/views/guides/edit.html.erb
<!-- Page Heading/Breadcrumbs -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header" style="text-align:center">Become a guide</h1>
  </div>
</div>

<div class="row">
  <!-- Alignment -->
  <div class="col-sm-offset-3 col-sm-6 col-lg-6 well well-sm">

    <%= form_for(@guide) do |formElement| %>
        <form class='form-horizontal'>
          <%= render 'shared/guide_error_messages' %>

          <div class='form-group'>
            <legend>Location</legend>

            <ul>
              <%= formElement.check_box :hood %>
              <%= formElement.label 'Mount Hood'%>
              <br>
              <%= formElement.check_box :bachelor %>
              <%= formElement.label 'Mount Bachelor' %>
              <br>
              <%= formElement.check_box :whistler %>
              <%= formElement.label 'Whistler'%>
            </ul>
          </div>

          <div class='form-group'>
            <legend>Specialties</legend>

            <ul>
              <%= formElement.check_box :downhill %>
              <%= formElement.label 'Downhill Skiing'%>
              <br>
              <%= formElement.check_box :crosscountry %>
              <%= formElement.label 'Crosscountry Skiing' %>
              <br>
              <%= formElement.check_box :snowboard %>
              <%= formElement.label 'Snowboarding'%>
              <br>
            </ul>
          </div>

          <div class="control-group">
            <legend>Rate</legend>
            <div class="controls">
              <div class="input-group">
                <div class="input-group-addon">$</div>
                <%= formElement.text_field :rate , class: 'form-control'%>
                <div class="input-group-addon">.00</div>
              </div>
            </div>
          </div>
          <br>

          <legend>Guide Information</legend>
          <div class="control-group">
            <div class="controls">
              <%= formElement.text_area :profile, 'rows' => 10, 'cols' => 100, class:'form-control' %>
            </div>
          </div>
          <br>

          <legend>Availability</legend>
          <div class='form-group'>
            <%= formElement.label 'Sunday', class: 'col-sm-2 control-label' %>
            <%= formElement.text_field :sun_avail, 'size' => 50, class:'form-control', style: 'width: 80%' %>
          </div>

          <div class='form-group'>
            <%= formElement.label 'Monday', class: 'col-sm-2 control-label' %>
            <%= formElement.text_field :mon_avail, 'size' => 50, class:'form-control', style: 'width: 80%' %>
          </div>

          <div class='form-group'>
            <%= formElement.label 'Tuesday', class: 'col-sm-2 control-label' %>
            <%= formElement.text_field :tues_avail, 'size' => 50, class:'form-control', style: 'width: 80%' %>
          </div>

          <div class='form-group'>
            <%= formElement.label 'Wednesday', class: 'col-sm-2 control-label' %>
            <%= formElement.text_field :wed_avail, 'size' => 50, class:'form-control', style: 'width: 80%' %>
          </div>

          <div class='form-group'>
            <%= formElement.label 'Thursday', class: 'col-sm-2 control-label' %>
            <%= formElement.text_field :thurs_avail, 'size' => 50, class: 'form-control', style: 'width: 80%' %>
          </div>

          <div class='form-group'>
            <%= formElement.label 'Friday', class: 'col-sm-2 control-label' %>
            <%= formElement.text_field :fri_avail, 'size' => 50, class:'form-control', style: 'width: 80%' %>
          </div>

          <div class='form-group'>
            <%= formElement.label 'Saturday', class: 'col-sm-2 control-label' %>
            <%= formElement.text_field :sat_avail, 'size' => 50, class:'form-control', style: 'width: 80%' %>
          </div>
          <div class="text-center">
          <div class='form-group'>
            <%= link_to "Cancel", edit_user_url(id: current_user.id),  class: "btn btn-danger"%>
            <%= formElement.submit 'Update', class: 'btn btn-success'%>
          </div>
          </div>
        </form>
    <% end %>
  </div>
</div>
<!-- Tracking -->
<script src="//cdn.optimizely.com/js/2718120061.js"></script>

app/views/guides/new.html.erb
<!-- Page Heading/Breadcrumbs -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header" style="text-align:center">Become a guide</h1>
  </div>
</div>

<div class="row">
  <!-- Alignment -->
  <div class="col-sm-offset-4 col-sm-6 col-lg-4 well well-sm">

    <%= form_for(@guide) do |formElement| %>
        <form class='form-horizontal'>
          <%= render 'shared/guide_error_messages' %>

          <div class='form-group'>
            <legend>Location</legend>

            <ul>
              <%= formElement.check_box :hood %>
              <%= formElement.label 'Mount Hood'%>
              <br>
              <%= formElement.check_box :bachelor %>
              <%= formElement.label 'Mount Bachelor' %>
              <br>
              <%= formElement.check_box :whistler %>
              <%= formElement.label 'Whistler'%>
            </ul>
          </div>

          <div class='form-group'>
            <legend>Specialties</legend>

            <ul>
              <%= formElement.check_box :downhill %>
              <%= formElement.label 'Downhill Skiing'%>
              <br>
              <%= formElement.check_box :crosscountry %>
              <%= formElement.label 'Crosscountry Skiing' %>
              <br>
              <%= formElement.check_box :snowboard %>
              <%= formElement.label 'Snowboarding'%>
              <br>
            </ul>
          </div>

          <div class="control-group">
          <legend>Rate</legend>
            <div class="controls">
              <div class="input-group">
                <div class="input-group-addon">$</div>
                <%= formElement.text_field :rate , class: 'form-control'%>
                <div class="input-group-addon">.00</div>
              </div>
            </div>
          </div>
          <br>

          <legend>Guide Information</legend>
          <div class="control-group">
            <div class="controls">
              <%= formElement.text_area :profile, 'rows' => 10, 'cols' => 100, class:'form-control' %>
            </div>
          </div>

          <legend>Availability</legend>
          <div class='form-group'>
            <%= formElement.label 'Sunday', class: 'col-sm-2 control-label' %>
            <%= formElement.text_field :sun_avail, 'size' => 50 %>
          </div>

          <div class='form-group'>
            <%= formElement.label 'Monday', class: 'col-sm-2 control-label' %>
            <%= formElement.text_field :mon_avail, 'size' => 50 %>
          </div>

          <div class='form-group'>
            <%= formElement.label 'Tuesday', class: 'col-sm-2 control-label' %>
            <%= formElement.text_field :tues_avail, 'size' => 50 %>
          </div>

          <div class='form-group'>
            <%= formElement.label 'Wednesday', class: 'col-sm-2 control-label' %>
            <%= formElement.text_field :wed_avail, 'size' => 50 %>
          </div>

          <div class='form-group'>
            <%= formElement.label 'Thursday', class: 'col-sm-2 control-label' %>
            <%= formElement.text_field :thurs_avail, 'size' => 50 %>
          </div>

          <div class='form-group'>
            <%= formElement.label 'Friday', class: 'col-sm-2 control-label' %>
            <%= formElement.text_field :fri_avail, 'size' => 50 %>
          </div>

          <div class='form-group'>
            <%= formElement.label 'Saturday', class: 'col-sm-2 control-label' %>
            <%= formElement.text_field :sat_avail, 'size' => 50 %>
          </div>

          <div class='form-group'>
            <%= link_to "Cancel", edit_user_url(id: current_user.id),  class: "btn btn-danger"%>
            <%= formElement.submit 'Become a guide!', class: 'btn btn-success'%>
          </div>

        </form>
    <% end %>
  </div>
</div>

app/views/guides/new_reservation.html.erb
    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header" style="text-align:center">
          Guide Reservation
        </h1>
      </div>
    </div>
    <!-- /.row -->
    <!-- Tracking -->
    <script src="//cdn.optimizely.com/js/2718120061.js"></script>
    <!-- Contact Guide -->
    <!-- other files have "jQuery" and "Bootstrap Core JavaScript" section that breaks tabs code in profile.html-->
    <div class="row">
      <div class="col-lg-12">
        <div id="contactGuide">
          <div class="row">
            <!-- Alignment -->
            <div class="col-sm-offset-3 col-sm-6">
              <!-- Form itself -->
              <%= form_for @reservation,
                  url: create_reservation_path,
                  html: { class: "well", id: @guide.id, method: "post" } do |formElement| %>
                <%= render 'shared/reservation_error_messages' %>

                <legend>To: <%= @guide.user.name %></legend>
                <div class="control-group">
                  <div class="controls">
                    <p><strong>From: </strong> <%= current_user.name %></p>
                    <p class="help-block"></p>
                  </div>
                </div>
                <div class="control-group">
                  <div class="controls">
                    <p><strong>Email: </strong> <%= current_user.email %></p>
                    <p class="help-block"></p>
                  </div>
                </div>
                <div class="control-group">
                  <div class="controls">
                    <p><strong>Price: </strong> <%= number_to_currency(@guide.rate) %> per hour</p>
                    <p class="help-block"></p>
                  </div>
                </div>
                <div class="control-group">
                  <div class="controls">
                    <%= formElement.label :location, class: 'control-label' %>
                    <%= formElement.select :location, options_for_select(locations) %>
                    <p class="help-block"></p>
                  </div>
                </div>
                <!-- Calendar Reservation -->
                <div class="control-group">
                  <label for="reservationtime">Reservation Times:</label>
                  <div class="input-group">
                    <span class="input-group-addon">
                      <i class="fa fa-calendar"></i>
                    </span>
                    <%= formElement.text_field :time,
                      class: "form-control",
                     # value: "01/22/2015 1:00 PM - 01/22/2015 1:30 PM",
                      required: true,
                      placeholder: "Date & time of your reservation",
                      id: "reservationtime"
                    %>
                    <script type="text/javascript">
                      $(document).ready(function() {
                          $('#reservationtime').daterangepicker({
                              timePicker: true,
                              timePickerIncrement: 30,
                              format: 'MM/DD/YYYY h:mm A'
                          }, function(start, end, label) {
                              console.log(start.toISOString(), end.toISOString(), label);
                          });
                      });
                    </script >
                  </div>
                </div>
                <br>
                <div class="control-group">
                  <div class="controls">
                    <div class="input-group">
                    <span class="input-group-addon">
                      <i class="fa fa-users"></i>
                    </span>
                    <%= formElement.number_field :number_of_people,
                      class: "form-control",
                      required: true,
                      placeholder: "Number of people in your team"
                    %>
                    </div>
                  </div>
                </div>
                <br>

                <div class="control-group">
                  <div class="controls">
                    <%= formElement.text_area :note,
                      class: "form-control",
                      rows: 10, cols: 100,
                      required: true,
                      placeholder: "Message to Guide"
                    %>
                    <p class="help-block"></p>
                  </div>
                </div>
                <div id="success"> </div> <!-- For success/fail messages -->
                <%= formElement.submit 'Submit', class: "btn btn-primary pull-right" %>
               <!--  #formElement.submit 'Send', class: 'btn btn-primary pull-right' %> -->
                  <!--%= link_to '<b>Submit</b>'.html_safe, payment_path, class: "btn btn-primary pull-right" %-->

                  <br>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- ./row -->

app/views/guides/show.html.erb
<% provide(:title, @guide.user.name) %>

<body>
  <!-- Page Content -->
  <div class="container">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Guide Profile
                <% if current_guide?(Guide.find_by(user_id: @guide.user_id)) %>
                    <%= link_to "Edit Guide Profile", edit_guide_url(id: @guide.id),  class: "btn btn-default"%>
                <% end %>
            </h1>
        </div>
    </div>
    <!-- /.row -->

    <!-- Guide Profile Section -->
    <div class="row">
      <!-- Main Guide Info: Name, Location, Sport, Pricing, Ratings -->
      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="col-xs-12 col-sm-5">
              <%= image_tag Gravatar.new(@guide.user.email).image_url(:d => :mm, :s => 300), class: 'img img-circle img-responsive full-width' %>
            </div>
            <div class="col-sm-offset-1 col-xs-12 col-sm-6">
              <h1><strong><%= @guide.user.name %></strong></h1>
              <h3><strong>Location: </strong><%= location_string(@guide.hood, @guide.bachelor, @guide.whistler) %> </h3>
              <h3><strong>Sports: </strong><%= sports_string(@guide.downhill, @guide.crosscountry, @guide.snowboard) %></h3>
              <h3><strong>Pricing: </strong><%= number_to_currency(@guide.rate) %>/hour</h3>
              <h3><strong>Rating: </strong>
                <% if @guide.reviews.count > 0 %>
                  <% stars = @guide.reviews.average(:rating).round %>
                  <% stars.times do |i| %>
                    <span class="fa fa-star"></span>
                  <% end %>
                  <% (5 - stars).times do |i| %>
                    <span class="fa fa-star-o"></span>
                  <% end %>
                <% else %>
                  No one has reviewed this guide yet. Be the first!
                <% end %>
              </h3>

              <!-- if user is logged in, then display appropriate buttons -->
              <% if logged_in? %>

                <% if !current_guide?(Guide.find_by(user_id: @guide.user_id)) %>
                  <%= link_to '<b>Reservation</b>'.html_safe, new_reservation_path, class: "btn btn-primary" %>
                  <!-- <i class="fa fa-book"></i> -->
                  <button type="button" class="btn btn-primary"
                    data-toggle="modal" data-target="#contactGuide">
                      <!-- <i class="fa fa-question-circle"></i> -->
                      <strong>Ask Guide a Question</strong>
                  </button>
                  <div class="modal fade" id="contactGuide" tabindex="-1"
                      role="dialog" aria-labelledby="myModalLabel"
                      aria-hidden="true" style="z-index:99999999999">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal"
                            aria-label="Close"><span aria-hidden="true">&times;</span>
                          </button>
                          <h3 class="modal-title" id="contactGuide">Ask Guide a Question</h3>
                        </div>
                        <div class="modal-body">
                          <%= form_for(Message.new) do |formElement| %>
                          <!--form name="sentMessage" id="contactGuide"  novalidate-->
                          <div class="control-group">
                            <div class="controls">
                              <div class='form-group'>

                                <%= formElement.label "From" %>
                                     <%= formElement.text_field :name, required: true, class: 'form-control', id: 'name',
                                       value: "#{current_user.name}", readonly: true %>

                              </div>
                            </div>
                          </div>
                          <div class="control-group">
                            <div class="controls">
                              <div class='form-group'>

                                <%= formElement.label :email %>
                                    <%= formElement.email_field :email, required: true, class: 'form-control', id: 'email',
                                    value: "#{current_user.email}", readonly: true %>

                                <!-- currenly viewing guide's email -->
                                <%= formElement.hidden_field :recipient_name, value: "#{@guide.user.name}" %>
                                <%= formElement.hidden_field :recipient_email, value: "#{@guide.user.email}" %>

                              </div>
                            </div>
                          </div>
                              <div class="control-group">
                                <div class="controls">
                                  <div class='form-group'>

                                    <%= formElement.hidden_field :subject, value: "Question" %>
                                    <%= formElement.label "Message" %>
                                    <%= formElement.text_area :content, required: true, class: 'form-control', id: 'message',
                                      placeholder: 'Question or Message', input_html: {rows: 10, cols: 100, minlength: '5',
                                      maxlength: '999', style: 'resize:none' } %>

                                  </div>
                                </div>
                                <p class="help-block"></p>
                              </div>
                            <div id="success"> </div> <!-- For success/fail messages -->
                          <!--/form-->
                        </div>
                        <div class="modal-footer">
                          <div class='form-group'>
                            <%= formElement.submit 'Submit', class: 'btn btn-success'%>
                          </div>
                        </div>
                        <% end %>
                      </div>
                    </div>
                  </div>
                <% end %>
                <!-- else if user is not logged in, redirect them to login page -->
              <% elsif !logged_in? %>
                <%= link_to '<b>Reservation</b>'.html_safe, "/login", class: "btn btn-primary" %>
                <%= link_to '<b>Ask Guide a Question </b>'.html_safe, "/login", class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Guide Profile Info Tab Navigation -->
    <ul id="myTab" class="nav nav-tabs nav-justified">
        <li class="active"><a href="#about-Me" data-toggle="tab">
          <i class="fa fa-child">
          </i> About Me</a>
        </li>
        <li class="">
          <a href="#availability" data-toggle="tab">
          <i class="fa fa-calendar"></i> Availability</a>
        </li>
        <li class="">
          <a href="#reviews" data-toggle="tab">
          <i class="fa fa-users"></i> Reviews</a>
        </li>
    </ul>

    <!-- Guide Profile Info Tab Content -->
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade active in col-sm-12" id="about-Me">
        <h3>About Me</h3>
        <p>
          <%= @guide.profile %>
        </p>
      </div>

      <div class="tab-pane fade col-sm-12" id="availability">
        <h3>Availability</h3>
        <table class="table table-striped">
          <tr>
            <td>Sunday</td>
            <td><%= @guide.sun_avail %></td>
          </tr>
          <tr>
            <td>Monday</td>
            <td><%= @guide.mon_avail %></td>
          </tr>
          <tr>
            <td>Tuesday</td>
            <td><%= @guide.tues_avail %></td>
          </tr>
          <tr>
            <td>Wednesday</td>
            <td><%= @guide.wed_avail %></td>
          </tr>
          <tr>
            <td>Thursday</td>
            <td><%= @guide.thurs_avail %></td>
          </tr>
          <tr>
            <td>Friday</td>
            <td><%= @guide.fri_avail %></td>
          </tr>
          <tr>
            <td>Saturday</td>
            <td><%= @guide.sat_avail %></td>
          </tr>
        </table>
      </div>

      <div class="tab-pane fade col-sm-12" id="reviews">
       <!-- <h3>Reviews</h3> -->
        <!-- Review Row -->
        <div class="row">
          <% if @guide.reviews.count > 0 %>
              <% for review in @guide.reviews %>
                <div class="col-md-2 text-center" style="padding-top:25px">
                  <p><%= image_tag Gravatar.new(review.user.email).image_url(:d => :mm) %></p>
                  <p><%= review.created_at %></p>
                </div>
                <div class="col-md-10">
                  <h3><% if !review.title.nil? then %><%=review.title%><% else %>Review Title<% end %></h3>
                  <!-- Rating stars -->
                  <% reviewRating = review.rating %>
                  <p>
                    <% reviewRating.times do |i| %>
                      <span class="fa fa-star"></span>
                    <% end %>
                    <% (5 - reviewRating).times do |i| %>
                      <span class="fa fa-star-o"></span>
                    <% end %>
                  </p>
                  <p>
                    by <%= review.user.name %>
                  </p>
                  <p>
                    <%= review.content %>
                  </p>
                  <br>
                </div>
              <% end %>
          <% end %>

        </div>
        <!-- /.row -->
      </div>
    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
</body>
<!-- Tracking -->
<script src="//cdn.optimizely.com/js/2718120061.js"></script>