config/routes.rb
Rails.application.routes.draw do

  root                                       'static_pages#home'
  get    'home'                           => 'static_pages#home'
  get    'contact'                        => 'messages#new'
  get    'locations'                      => 'static_pages#locations'
  get    'about'                          => 'static_pages#about'
  get    'faq'                            => 'static_pages#faq'
  get    'search'                         => 'static_pages#search'
  post   'search'                         => 'static_pages#search'
  get    'mtbachelor'                     => 'guides#mtbachelor'
  get    'mthood'                         => 'guides#mthood'
  get    'mtwhistler'                     => 'guides#mtwhistler'
  get    'guides/:id/new-reservation'     => 'guides#new_reservation', as: :new_reservation
  get    'guides/:id/payment'             => 'guides#payment', as: :payment
  post   'reservation/:id/create'         => 'reservations#create', as: :create_reservation
  get    'users/:id/change_password'      => 'users#change_password', as: 'change_password'
  get    'signup'                         => 'users#new'
  get    'login'                          => 'sessions#new'
  get    'users/:id/transactions'         => 'users#transaction_history', as: 'transactions'
  get    'users/:id/review'               => 'users#review', as: 'review'
  post   'review'                         => 'reviews#new'
  post   'login'                          => 'sessions#create'
  delete 'logout'                         => 'sessions#destroy'
  get    'guides'                         => 'guides#index', as: 'index'

  resources :users
  resources :guides
  resources :messages
  resources :reviews

end

app/views/layouts/_footer.html.erb
<footer class="navbar container"  style="width:100% ; background:#d3d3d3 ; max-width:inherit">
  <div class="row text-center center-block">
    <div class="col-md-4">
      <h4>User Information</h4>
      <ul class="list-unstyled" style="color:#777777">
        <li><%= link_to "Get Started", signup_path %></li>
        <li><a href="">Services</a></li>
        <li><a href="">Guides</a></li>
        <li><%= link_to "All Locations", locations_path %></li>
        <li><%= link_to "FAQ", faq_path %></li>
      </ul>
    </div>
    <div class="col-md-4">
      <h4>Guide Information</h4>
      <ul class="list-unstyled" style="color:#777777">
        <li><a href="">Become Guide</a></li>
        <li><a href="">Payment Process</a></li>
        <li><a href="">How It Works</a></li>
        <li><a href="">Legal</a></li>
      </ul>
    </div>
    <div class="col-md-4">
      <h4>Corporate</h4>
      <ul class="list-unstyled" style="color:#777777">
        <li><%= link_to "Contact Us", contact_path %></li>
        <li><a href="">Legal</a></li>
        <li><a href="">Mission</a></li>
        <li><a href="">Careers</a></li>
        <li><a href="">Expansion</a></li>
      </ul>
    </div>
  </div>
  <div class="text-center">
    <p>
      <br><br>
      Copyright &copy; Radventure 2015
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">RADVENTURE</a>
    </div>

    <div class="collapse navbar-collapse nav navbar-nav navbar-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Search", search_path %></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Location<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Locations", locations_path %></li>
            <li><%= link_to "Mt. Hood", mthood_path %></li>
            <li><%= link_to "Mt. Bachelor", mtbachelor_path %></li>
            <li><%= link_to "Mt. Whistler", mtwhistler_path %></li>
          </ul>
        </li>

     <!--   <li><a href="search.html">Quick Search</a></li> -->

        <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                 role="button" aria-expanded="false">Account
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <% if is_guide? %>
                  <li><%= link_to "Profile", current_guide %></li>
                  <li><%= link_to "Update Profile", edit_guide_path(current_guide) %></li>
                <% end %>
                <li><%= link_to "Account Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Change Password", change_password_url(current_user.id) %></li>

                <li class="divider"></li>
                <li><%= link_to "Log out", logout_path, method: "delete" %></li>
              </ul>
            </li>

        <% else %>
            <li>
              <button type="button" class="btn btn-md navbar-btn" data-toggle="modal" data-target="#LogIn" style="margin-left:15px">
                Log in
              </button>
            </li>
            <li>
              <%= button_to "Sign up", signup_path, class: 'btn btn-md navbar-btn', style: 'margin-left:15px', method: 'get' %>
            </li>
        <% end %>

        <div class="modal fade" id="LogIn" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="z-index:99999999999">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="LogInModal">Login</h4>
              </div>
              <div class="modal-body">
                <%= form_for(:session, url: login_path) do |formElement| %>
                    <form>
                      <!--%= render 'shared/error_messages' %-->

                      <div class='form-group'>
                        <%= formElement.label :Email %>
                        <%= formElement.email_field :email,  class: 'form-control', id: 'Username', placeholder: 'radventureit@gmail.com' %>
                      </div>

                      <div class='form-group'>
                        <%= formElement.label :password%>
                        <%= formElement.password_field :password, class: 'form-control', id: 'Password', placeholder: 'Password' %>
                      </div>
                      <div class='form-group'>
                        <%= formElement.submit "Submit", class: 'btn btn-default' %>
                      </div>

                    </form>
                <% end %>
              </div>
            </div>
          </div>
        </div>

      </ul>
    </div> <!-- /.navbar-collapse -->
  </div> <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="//cdn.optimizely.com/js/2718120061.js"></script>
    <title>GoRadVenture</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'daterangepicker' %>
    <%= javascript_include_tag 'moment' %>
    <%= csrf_meta_tags %>

<!--
    <script src="../javascripts/daterangepicker.js"></script>
    <script src="../javascripts/moment.js"></script>


    <link href="../stylesheets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS
    <link href="../stylesheets/modern-business.css" rel="stylesheet">
    <link href="../stylesheets/daterangepicker-bs3.css" rel="stylesheet" type="text/css"/>

    <!-- Custom Fonts
    <link href="../stylesheets/font-awesome.min.css" rel="stylesheet" type="text/css"> -->

  </head>
  <body>
    <%= render 'layouts/header' %>

    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>


    <%= yield %>

    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>

  </body>
</html>